// ═══════════════════════════════════════════════════════════
//  SENTENCES DATA – Drag & Drop Sentence Builder
//  120 sentences: 30 per level (A1, A2, B1, B2)
//  Each sentence: { he, tr, words }
//    he    – Hebrew translation (prompt)
//    tr    – Full Turkish sentence (reference)
//    words – Array of Turkish words in correct order (tiles)
// ═══════════════════════════════════════════════════════════

const SENTENCES = {
  A1: [
    { he: 'אני ישראלי',                        tr: 'Ben bir İsrailliyim',           words: ['Ben', 'bir', 'İsrailliyim'] },
    { he: 'השם שלי אליס',                      tr: 'Benim adım Alice',              words: ['Benim', 'adım', 'Alice'] },
    { he: 'אני לומד טורקית',                   tr: 'Ben Türkçe öğreniyorum',        words: ['Ben', 'Türkçe', 'öğreniyorum'] },
    { he: 'היום מזג האוויר יפה מאוד',          tr: 'Bugün hava çok güzel',          words: ['Bugün', 'hava', 'çok', 'güzel'] },
    { he: 'אני תלמיד',                         tr: 'Ben bir öğrenciyim',            words: ['Ben', 'bir', 'öğrenciyim'] },
    { he: 'כוס מים בבקשה',                     tr: 'Bir bardak su lütfen',          words: ['Bir', 'bardak', 'su', 'lütfen'] },
    { he: 'איפה השירותים?',                    tr: 'Tuvalet nerede acaba?',         words: ['Tuvalet', 'nerede', 'acaba?'] },
    { he: 'כמה זה עולה?',                      tr: 'Bu ne kadar para?',             words: ['Bu', 'ne', 'kadar', 'para?'] },
    { he: 'אני לא יודע טורקית טוב',            tr: 'Türkçe çok iyi bilmiyorum',     words: ['Türkçe', 'çok', 'iyi', 'bilmiyorum'] },
    { he: 'תוכל לחזור בבקשה?',                 tr: 'Lütfen tekrar söyler misin?',   words: ['Lütfen', 'tekrar', 'söyler', 'misin?'] },
    { he: 'תודה רבה לך',                       tr: 'Çok teşekkür ederim',           words: ['Çok', 'teşekkür', 'ederim'] },
    { he: 'נתראה מחר',                         tr: 'Yarın görüşürüz',               words: ['Yarın', 'görüşürüz'] },
    { he: 'אני מאחל יום טוב',                  tr: 'İyi günler dilerim',            words: ['İyi', 'günler', 'dilerim'] },
    { he: 'אני גר באיסטנבול',                  tr: 'Ben İstanbul\'da yaşıyorum',    words: ['Ben', 'İstanbul\'da', 'yaşıyorum'] },
    { he: 'אמא שלי מאוד טובה',                 tr: 'Annem çok iyi',                 words: ['Annem', 'çok', 'iyi'] },
    { he: 'אבא שלי רופא',                      tr: 'Babam bir doktor',              words: ['Babam', 'bir', 'doktor'] },
    { he: 'יש לי אח',                          tr: 'Bir kardeşim var',              words: ['Bir', 'kardeşim', 'var'] },
    { he: 'אני בן עשרים',                      tr: 'Ben yirmi yaşındayım',          words: ['Ben', 'yirmi', 'yaşındayım'] },
    { he: 'זה ספר?',                           tr: 'Bu bir kitap mı?',              words: ['Bu', 'bir', 'kitap', 'mı?'] },
    { he: 'האוכל מאוד טעים',                   tr: 'Yemek çok lezzetli',            words: ['Yemek', 'çok', 'lezzetli'] },
    { he: 'היום יום שני',                      tr: 'Bugün pazartesi günü',          words: ['Bugün', 'pazartesi', 'günü'] },
    { he: 'עכשיו מה השעה?',                    tr: 'Şimdi saat kaç?',               words: ['Şimdi', 'saat', 'kaç?'] },
    { he: 'מזג האוויר מאוד קר היום',           tr: 'Hava çok soğuk bugün',          words: ['Hava', 'çok', 'soğuk', 'bugün'] },
    { he: 'אני מאוד רעב',                      tr: 'Ben çok açım',                  words: ['Ben', 'çok', 'açım'] },
    { he: 'בוא לפה בבקשה',                     tr: 'Buraya gel lütfen',             words: ['Buraya', 'gel', 'lütfen'] },
    { he: 'אני אוהב אותך',                     tr: 'Ben seni seviyorum',            words: ['Ben', 'seni', 'seviyorum'] },
    { he: 'לאן אתה הולך?',                     tr: 'Nereye gidiyorsun?',            words: ['Nereye', 'gidiyorsun?'] },
    { he: 'אני הולך הביתה',                    tr: 'Ben eve gidiyorum',             words: ['Ben', 'eve', 'gidiyorum'] },
    { he: 'זה מאוד יקר',                       tr: 'Bu çok pahalı',                 words: ['Bu', 'çok', 'pahalı'] },
    { he: 'אין לי מכונית',                     tr: 'Benim arabam yok',              words: ['Benim', 'arabam', 'yok'] },
  ],

  A2: [
    { he: 'אתמול הלכתי לקולנוע',               tr: 'Dün sinemaya gittim',                 words: ['Dün', 'sinemaya', 'gittim'] },
    { he: 'מחר אני נוסע לאיסטנבול',            tr: 'Yarın İstanbul\'a gideceğim',         words: ['Yarın', 'İstanbul\'a', 'gideceğim'] },
    { he: 'בבוקר אכלתי ארוחת בוקר',            tr: 'Sabah kahvaltı yaptım',               words: ['Sabah', 'kahvaltı', 'yaptım'] },
    { he: 'הערב נצפה בסרט',                    tr: 'Bu akşam film izleyeceğiz',           words: ['Bu', 'akşam', 'film', 'izleyeceğiz'] },
    { he: 'בשבוע שעבר הייתי חולה',             tr: 'Geçen hafta hasta oldum',             words: ['Geçen', 'hafta', 'hasta', 'oldum'] },
    { he: 'כל יום אני עושה ספורט',             tr: 'Her gün spor yapıyorum',              words: ['Her', 'gün', 'spor', 'yapıyorum'] },
    { he: 'קניתי לך מתנה',                     tr: 'Sana bir hediye aldım',               words: ['Sana', 'bir', 'hediye', 'aldım'] },
    { he: 'יש לי שני ילדים',                   tr: 'Benim iki çocuğum var',               words: ['Benim', 'iki', 'çocuğum', 'var'] },
    { he: 'מחר יהיה גשום',                     tr: 'Yarın hava yağmurlu olacak',          words: ['Yarın', 'hava', 'yağmurlu', 'olacak'] },
    { he: 'שכחתי את שמך',                      tr: 'Ben senin adını unuttum',             words: ['Ben', 'senin', 'adını', 'unuttum'] },
    { he: 'המסעדה הזאת מאוד יפה',              tr: 'Bu restoran çok güzel',               words: ['Bu', 'restoran', 'çok', 'güzel'] },
    { he: 'אני שותה את הקפה עם חלב',           tr: 'Kahveyi sütlü içerim',                words: ['Kahveyi', 'sütlü', 'içerim'] },
    { he: 'אתמול בלילה שכבתי מאוחר',           tr: 'Dün gece geç yattım',                 words: ['Dün', 'gece', 'geç', 'yattım'] },
    { he: 'אני מחפש עבודה חדשה',               tr: 'Yeni bir iş arıyorum',                words: ['Yeni', 'bir', 'iş', 'arıyorum'] },
    { he: 'אני רוצה ללמוד טורקית',             tr: 'Türkçe öğrenmek istiyorum',           words: ['Türkçe', 'öğrenmek', 'istiyorum'] },
    { he: 'קראת את הספר הזה?',                 tr: 'Bu kitabı okudun mu?',                words: ['Bu', 'kitabı', 'okudun', 'mu?'] },
    { he: 'תוכל לעזור לי?',                    tr: 'Bana yardım eder misin?',             words: ['Bana', 'yardım', 'eder', 'misin?'] },
    { he: 'המשפחה שלי חיה בישראל',             tr: 'Ailem İsrail\'de yaşıyor',            words: ['Ailem', 'İsrail\'de', 'yaşıyor'] },
    { he: 'מחר אני יוצא לחופשה',               tr: 'Yarın tatile çıkacağım',              words: ['Yarın', 'tatile', 'çıkacağım'] },
    { he: 'האוכל הזה מאוד מלוח',               tr: 'Bu yemek çok tuzlu',                  words: ['Bu', 'yemek', 'çok', 'tuzlu'] },
    { he: 'תפתח את הדלת בבקשה?',               tr: 'Kapıyı açar mısın?',                  words: ['Kapıyı', 'açar', 'mısın?'] },
    { he: 'היום אני מאוד עייף',                tr: 'Bugün çok yorgunum',                  words: ['Bugün', 'çok', 'yorgunum'] },
    { he: 'בואו ניפגש בשמונה',                 tr: 'Saat sekizde buluşalım',              words: ['Saat', 'sekizde', 'buluşalım'] },
    { he: 'אני מאוד אוהב את השיר הזה',         tr: 'Bu şarkıyı çok seviyorum',            words: ['Bu', 'şarkıyı', 'çok', 'seviyorum'] },
    { he: 'אתמול אכלתי עם החברים שלי',         tr: 'Dün arkadaşlarımla yedim',            words: ['Dün', 'arkadaşlarımla', 'yedim'] },
    { he: 'קנינו בית חדש',                     tr: 'Yeni bir ev aldık',                   words: ['Yeni', 'bir', 'ev', 'aldık'] },
    { he: 'תיתן לי את מספר הטלפון שלך?',       tr: 'Telefon numaranı verir misin?',       words: ['Telefon', 'numaranı', 'verir', 'misin?'] },
    { he: 'אבא שלי חוזר מחר',                  tr: 'Babam yarın dönüyor',                 words: ['Babam', 'yarın', 'dönüyor'] },
    { he: 'הכרטיס הזה היה מאוד יקר',           tr: 'Bu bilet çok pahalıydı',              words: ['Bu', 'bilet', 'çok', 'pahalıydı'] },
    { he: 'אחותי מאוד יפה',                    tr: 'Kız kardeşim çok güzel',              words: ['Kız', 'kardeşim', 'çok', 'güzel'] },
  ],

  B1: [
    { he: 'אם יירד גשם אני אשאר בבית',             tr: 'Eğer yağmur yağarsa evde kalırım',        words: ['Eğer', 'yağmur', 'yağarsa', 'evde', 'kalırım'] },
    { he: 'לדעתי הסרט הזה היה מאוד טוב',           tr: 'Bence bu film çok güzeldi',               words: ['Bence', 'bu', 'film', 'çok', 'güzeldi'] },
    { he: 'כשנסעתי לטורקיה הייתי מאוד שמח',        tr: 'Türkiye\'ye gittiğimde çok mutluydum',    words: ['Türkiye\'ye', 'gittiğimde', 'çok', 'mutluydum'] },
    { he: 'כשאני מבשל אני שומע מוזיקה',            tr: 'Yemek yaparken müzik dinlerim',           words: ['Yemek', 'yaparken', 'müzik', 'dinlerim'] },
    { he: 'מעולם לא הייתי בפריז',                  tr: 'Daha önce hiç Paris\'e gitmedim',         words: ['Daha', 'önce', 'hiç', 'Paris\'e', 'gitmedim'] },
    { he: 'הוא אמר שלא אוכל לבוא היום',            tr: 'Bugün gelemeyeceğimi söyledi',            words: ['Bugün', 'gelemeyeceğimi', 'söyledi'] },
    { he: 'הלוואי שהיית בא מוקדם יותר',            tr: 'Keşke daha erken gelseydin',              words: ['Keşke', 'daha', 'erken', 'gelseydin'] },
    { he: 'אני ממליץ לך לקרוא את הספר הזה',        tr: 'Bu kitabı okumanı tavsiye ederim',        words: ['Bu', 'kitabı', 'okumanı', 'tavsiye', 'ederim'] },
    { he: 'כשתחזור תתקשר אליי',                    tr: 'Ne zaman dönersen ara beni',              words: ['Ne', 'zaman', 'dönersen', 'ara', 'beni'] },
    { he: 'אני לא יודע מה הוא חושב',               tr: 'Onun ne düşündüğünü bilmiyorum',          words: ['Onun', 'ne', 'düşündüğünü', 'bilmiyorum'] },
    { he: 'לא נשארנו כי המלון היה יקר',            tr: 'Bu otel çok pahalı olduğu için kalmadık', words: ['Bu', 'otel', 'çok', 'pahalı', 'olduğu', 'için', 'kalmadık'] },
    { he: 'יש משהו שאני יכול לעשות?',              tr: 'Yapabileceğim bir şey var mı?',           words: ['Yapabileceğim', 'bir', 'şey', 'var', 'mı?'] },
    { he: 'אני יודע גם טורקית וגם עברית',          tr: 'Hem Türkçe hem İbranice biliyorum',       words: ['Hem', 'Türkçe', 'hem', 'İbranice', 'biliyorum'] },
    { he: 'לא הצלחתי לענות על השאלה הזאת',         tr: 'Bu soruyu cevaplayamadım',                words: ['Bu', 'soruyu', 'cevaplayamadım'] },
    { he: 'כמה שאני לומד אני לא מבין',             tr: 'Ne kadar çalışsam da anlamıyorum',        words: ['Ne', 'kadar', 'çalışsam', 'da', 'anlamıyorum'] },
    { he: 'אני חושב שאאחר',                        tr: 'Geç kalacağımı düşünüyorum',              words: ['Geç', 'kalacağımı', 'düşünüyorum'] },
    { he: 'הלכת מבלי להגיד לי',                    tr: 'Bana söylemeden gittin',                  words: ['Bana', 'söylemeden', 'gittin'] },
    { he: 'שמחתי מאוד לראות אותו',                 tr: 'Onu gördüğüme çok sevindim',              words: ['Onu', 'gördüğüme', 'çok', 'sevindim'] },
    { he: 'אנחנו צריכים לעשות את זה יחד',          tr: 'Bu işi birlikte yapmalıyız',              words: ['Bu', 'işi', 'birlikte', 'yapmalıyız'] },
    { he: 'אני יכול לשאול אותך משהו?',             tr: 'Sana bir şey sorabilir miyim?',           words: ['Sana', 'bir', 'şey', 'sorabilir', 'miyim?'] },
    { he: 'לא הצלחתי לבוא כי הייתי עסוק מאוד',     tr: 'Çok yoğun olduğum için gelemedim',        words: ['Çok', 'yoğun', 'olduğum', 'için', 'gelemedim'] },
    { he: 'בעצם אני מאוד מתגעגע אליך',             tr: 'Aslında seni çok özlüyorum',              words: ['Aslında', 'seni', 'çok', 'özlüyorum'] },
    { he: 'אתה צריך לנוח קצת',                     tr: 'Biraz dinlenmen gerekiyor',               words: ['Biraz', 'dinlenmen', 'gerekiyor'] },
    { he: 'ללמוד שפה חדשה זה קשה',                 tr: 'Yeni bir dil öğrenmek zor',               words: ['Yeni', 'bir', 'dil', 'öğrenmek', 'zor'] },
    { he: 'האם מחר ירד גשם?',                      tr: 'Acaba yarın yağmur yağar mı?',            words: ['Acaba', 'yarın', 'yağmur', 'yağar', 'mı?'] },
    { he: 'ראיתי את הסרט הזה בעבר',                tr: 'Bu filmi daha önce izlemiştim',           words: ['Bu', 'filmi', 'daha', 'önce', 'izlemiştim'] },
    { he: 'חשוב לי מאוד שתסמוך עליי',              tr: 'Bana güvenmen çok önemli',                words: ['Bana', 'güvenmen', 'çok', 'önemli'] },
    { he: 'אני חושב שכולם יודעים את זה',           tr: 'Herkes bunu biliyor sanırım',             words: ['Herkes', 'bunu', 'biliyor', 'sanırım'] },
    { he: 'התגעגעתי אליך, מה שלומך?',              tr: 'Seni özledim, nasılsın?',                 words: ['Seni', 'özledim,', 'nasılsın?'] },
    { he: 'היית צודק',                             tr: 'Sen haklıydın',                           words: ['Sen', 'haklıydın'] },
  ],

  B2: [
    { he: 'לא קיבלתי את ההחלטה שהתקבלה אתמול',               tr: 'Dün verilen kararı kabul etmedim',                       words: ['Dün', 'verilen', 'kararı', 'kabul', 'etmedim'] },
    { he: 'אני לא יכול ללכת לפני שהבעיה הזאת נפתרת',         tr: 'Bu sorun çözülmedikçe gidemem',                          words: ['Bu', 'sorun', 'çözülmedikçe', 'gidemem'] },
    { he: 'אם היית בא מוקדם יותר היית יכול לראות',           tr: 'Eğer daha erken gelmiş olsaydın görebilirdin',           words: ['Eğer', 'daha', 'erken', 'gelmiş', 'olsaydın', 'görebilirdin'] },
    { he: 'למרות שאמרנו לו הוא לא הקשיב',                    tr: 'Ona söylememize rağmen dinlemedi',                       words: ['Ona', 'söylememize', 'rağmen', 'dinlemedi'] },
    { he: 'אנחנו צריכים לדבר על הנושא הזה אחר כך',           tr: 'Bu konuyu sonra konuşmamız gerek',                       words: ['Bu', 'konuyu', 'sonra', 'konuşmamız', 'gerek'] },
    { he: 'למיטב ידיעתי מחר חופשה',                          tr: 'Bildiğim kadarıyla yarın tatil',                         words: ['Bildiğim', 'kadarıyla', 'yarın', 'tatil'] },
    { he: 'כדי להצליח אתה צריך לעבוד קשה',                   tr: 'Başarılı olmak için çok çalışman lazım',                 words: ['Başarılı', 'olmak', 'için', 'çok', 'çalışman', 'lazım'] },
    { he: 'לעולם לא אשכח את מה שקרה אז',                     tr: 'O zaman olanları hiç unutmayacağım',                     words: ['O', 'zaman', 'olanları', 'hiç', 'unutmayacağım'] },
    { he: 'הלוואי שיכולתי לומר לך בזמן',                     tr: 'Keşke sana zamanında söyleyebilseydim',                  words: ['Keşke', 'sana', 'zamanında', 'söyleyebilseydim'] },
    { he: 'לא משנה מה יקרה, אתמוך בך',                       tr: 'Her ne olursa olsun seni destekleyeceğim',               words: ['Her', 'ne', 'olursa', 'olsun', 'seni', 'destekleyeceğim'] },
    { he: 'אני תוהה מה אתה חושב על העניין הזה',              tr: 'Bu mesele hakkında ne düşündüğünü merak ediyorum',       words: ['Bu', 'mesele', 'hakkında', 'ne', 'düşündüğünü', 'merak', 'ediyorum'] },
    { he: 'כשהיינו ילדים היינו משחקים פה',                   tr: 'Çocukken burada oynardık',                               words: ['Çocukken', 'burada', 'oynardık'] },
    { he: 'בחיים שום דבר אינו מקרי',                         tr: 'Hayatta hiçbir şey tesadüf değildir',                    words: ['Hayatta', 'hiçbir', 'şey', 'tesadüf', 'değildir'] },
    { he: 'אני צריך לקחת אחריות על ההחלטה הזאת',             tr: 'Bu kararın sorumluluğunu almam gerekir',                 words: ['Bu', 'kararın', 'sorumluluğunu', 'almam', 'gerekir'] },
    { he: 'אני באמת לא מבין מה אתה רוצה',                    tr: 'Gerçekten ne istediğini anlayamıyorum',                  words: ['Gerçekten', 'ne', 'istediğini', 'anlayamıyorum'] },
    { he: 'לא השגתי את ההצלחה הזאת במקרה',                   tr: 'Bu başarıyı tesadüf eseri elde etmedim',                 words: ['Bu', 'başarıyı', 'tesadüf', 'eseri', 'elde', 'etmedim'] },
    { he: 'כל אחד צריך ללמוד מהטעויות שלו',                  tr: 'Herkes kendi hatalarından ders almalı',                  words: ['Herkes', 'kendi', 'hatalarından', 'ders', 'almalı'] },
    { he: 'אני לא מאמין למה שהוא אומר',                      tr: 'Onun söylediklerine inanmıyorum',                        words: ['Onun', 'söylediklerine', 'inanmıyorum'] },
    { he: 'זה יהיה טוב יותר ממה שדמיינת',                    tr: 'Hayal ettiğinden daha iyi olacak',                       words: ['Hayal', 'ettiğinden', 'daha', 'iyi', 'olacak'] },
    { he: 'אתה צריך להיות זהיר מאוד כשאתה עושה את זה',       tr: 'Bunu yaparken çok dikkatli olmalısın',                   words: ['Bunu', 'yaparken', 'çok', 'dikkatli', 'olmalısın'] },
    { he: 'הבנתי בדיוק למה התכוונת',                         tr: 'Neyi kastettiğini tam olarak anladım',                   words: ['Neyi', 'kastettiğini', 'tam', 'olarak', 'anladım'] },
    { he: 'אני מקווה שהכל יסתדר',                            tr: 'Umarım her şey yoluna girer',                            words: ['Umarım', 'her', 'şey', 'yoluna', 'girer'] },
    { he: 'אני לא רוצה שתבין אותי לא נכון',                  tr: 'Beni yanlış anlamanı istemem',                           words: ['Beni', 'yanlış', 'anlamanı', 'istemem'] },
    { he: 'הקשר בינינו חזק מאוד',                            tr: 'Aramızdaki bağ çok güçlü',                               words: ['Aramızdaki', 'bağ', 'çok', 'güçlü'] },
    { he: 'אני לא בקיא בנושא הזה',                           tr: 'Bu konuda bilgi sahibi değilim',                         words: ['Bu', 'konuda', 'bilgi', 'sahibi', 'değilim'] },
    { he: 'אין לי יותר זמן לחכות',                           tr: 'Daha fazla bekleyecek vaktim yok',                       words: ['Daha', 'fazla', 'bekleyecek', 'vaktim', 'yok'] },
    { he: 'ההצלחה שלך גרמה לי גאווה רבה',                    tr: 'Bunu başarman beni çok gurur duyurdu',                   words: ['Bunu', 'başarman', 'beni', 'çok', 'gurur', 'duyurdu'] },
    { he: 'תהיה מכבד כשאנשים מדברים איתך',                   tr: 'İnsanlar seninle konuşurken saygılı ol',                 words: ['İnsanlar', 'seninle', 'konuşurken', 'saygılı', 'ol'] },
    { he: 'לא נשאר שום דבר שאנחנו יכולים לעשות',             tr: 'Yapabileceğimiz hiçbir şey kalmadı',                     words: ['Yapabileceğimiz', 'hiçbir', 'şey', 'kalmadı'] },
    { he: 'אני מחפש מקום שקט',                               tr: 'Sessiz bir yer arıyorum',                                words: ['Sessiz', 'bir', 'yer', 'arıyorum'] },
  ],
};

// Expose globally
if (typeof window !== 'undefined') {
  window.SENTENCES = SENTENCES;
}
